# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
cran: https://cran.rstudio.com
matrix:
  include:
    - r: release
      deploy:
        provider: script
        script:
          - bash code/deploy.sh
        skip_cleanup: true
        on:
          branch: master
